name: Mirror Merged PRs from Upstream

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  mirror_prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the downstream repository
      uses: actions/checkout@v2
      with:
        repository: TerraTheUnwisest/PlanetoidSS14
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0 # Fetch all history for all branches

    - name: Fetch PRs from upstream
      run: |
        git remote add upstream https://github.com/space-wizards/space-station-14.git
        git fetch upstream

    - name: Create mirrored PR tracking file if not exists
      run: |
        if [ ! -f mirrored_prs.txt ]; then
          touch mirrored_prs.txt
        fi
        git add mirrored_prs.txt
        git commit -m "Ensure mirrored PRs tracking file exists" || true
        git push origin master

    - name: List merged PRs
      id: list_prs
      run: |
        curl -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/space-wizards/space-station-14/pulls?state=closed \
          | jq '.[] | select(.merged_at != null) | .number' > merged_prs.txt
        cat merged_prs.txt

    - name: Process merged PRs
      run: |
        # Track already mirrored PRs
        mirrored_prs=$(cat mirrored_prs.txt || echo "")

        while read pr_number; do
          if echo "$mirrored_prs" | grep -Fxq "$pr_number"; then
            echo "PR $pr_number already mirrored, skipping..."
            continue
          fi

          # Get PR details
          pr=$(curl -H "Authorization: token ${{ secrets.GH_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/space-wizards/space-station-14/pulls/$pr_number)

          pr_title=$(echo $pr | jq -r '.title')
          pr_body=$(echo $pr | jq -r '.body')
          pr_merge_commit=$(echo $pr | jq -r '.merge_commit_sha')
          pr_base_branch=$(echo $pr | jq -r '.base.ref')

          # Debugging logs
          echo "PR Number: $pr_number"
          echo "PR Title: $pr_title"
          echo "PR Body: $pr_body"
          echo "PR Merge Commit: $pr_merge_commit"
          echo "PR Base Branch: $pr_base_branch"

          # Stash any local changes
          git stash

          # Create a new branch from the base branch
          git checkout -b mirror-pr-$pr_number origin/$pr_base_branch

          # Cherry-pick the merge commit of the PR
          git cherry-pick $pr_merge_commit

          # Push the new branch to the downstream repository
          git push origin mirror-pr-$pr_number

          # Create a new PR in the downstream repository
          pr_response=$(curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/TerraTheUnwisest/PlanetoidSS14/pulls \
            -d "$(jq -n --arg title "MIRROR: $pr_title" --arg body "$pr_body" --arg base "master" --arg head "mirror-pr-$pr_number" \
              '{title: $title, body: $body, base: $base, head: $head}')")

          # Check if the PR was successfully created
          pr_url=$(echo $pr_response | jq -r '.html_url')
          if [ "$pr_url" != "null" ]; then
            echo "Successfully created PR: $pr_url"
            # Add PR number to mirrored_prs.txt
            echo "$pr_number" >> mirrored_prs.txt
          else
            echo "Failed to create PR for $pr_number"
            git push origin --delete mirror-pr-$pr_number
            git branch -D mirror-pr-$pr_number
          fi

          # Clean up the branch locally
          git checkout master
          git branch -D mirror-pr-$pr_number

          # Apply stashed changes
          git stash pop || true

        done < merged_prs.txt

    - name: Push updates to mirrored PRs tracking file
      run: |
        git add mirrored_prs.txt
        git commit -m "Update mirrored PRs tracking file"
        git push origin master

    - name: Clean up
      run: |
        rm merged_prs.txt
